(require 'pdf-tools)
(pdf-tools-install)
(shell-command "xmodmap ~/nix-config/keyboard.xmodmap")
(shell-command "xmodmap ~/nix-config/keyboard.xmodmap")
(shell-command "xmodmap ~/nix-config/keyboard.xmodmap")
(shell-command "xmodmap ~/nix-config/keyboard.xmodmap")

(global-set-key (kbd "s-u") (lambda () (interactive) (shell-command "amixer set Master 10%+")))
(global-set-key (kbd "s-d") (lambda () (interactive) (shell-command "amixer set Master 10%-")))
(global-set-key (kbd "s-m") (lambda () (interactive) (shell-command "amixer set Master toggle")))
